import type { Metadata } from "next";
import { Averia_Sans_Libre, Herr_Von_Muellerhoff, IBM_Plex_Mono, IBM_Plex_Sans, Inter, Lato, Lora, Montserrat, Open_Sans, Poppins, Roboto, Source_Sans_3, Source_Serif_4, Ubuntu } from "next/font/google";
import Head from "next/head";
import icon from "../public/favicon.ico"

const poppins = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Portifólio pessoal",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="pt-BR">
      <Head>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={`${poppins.className} .relative z-0 overflow-x-hidden`}>{children}</body>
    </html>
  );
};

export default RootLayout;
