import "./styles/globals.css";
import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import Head from "next/head";

const lato = League_Spartan({
  weight: ["400", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portifólio pessoal",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="pt-BR">
      <Head>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={lato.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
