import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import Head from "next/head";
// import icon from "../public/icon.svg"
// ! ADICIONAR FAVICON
const IBMPlexSans = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Portifólio pessoal",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="pt-BR">
      <Head>
        <link rel="icon" href="/icon.sgv" />
      </Head>
      <body className={`${IBMPlexSans.className} .relative z-0 overflow-x-hidden`}>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
// ! fazer uma página de errro 404 personalizada